[package]
name = "backoff"
version = "0.1.2-pre"
authors = ["Tibor Benke <ihrwein@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ihrwein/backoff"
homepage = "https://github.com/ihrwein/backoff"
documentation = "https://docs.rs/backoff"
categories = ["network-programming"]
description = """
Retry operations with exponential backoff policy.
"""

[badges]
travis-ci = { repository = "ihrwein/backoff" }

[dependencies]
rand = "0.3.15"

[dev-dependencies]
reqwest = "0.6"